Repository MIT-Emerging-Talent/2024-group-03-cdsp, pull requests merged in 2024-02, with the labels that each got.

#3 Restrospective, research question, problem statement
  .collaboration/README.md
  .collaboration/communication.md
  .collaboration/learning_goals.md
  .collaboration/retrospective/.template_retrospective.md
  .collaboration/retrospective/milestone1-retrospective.md
  milestones/1.problem_identification/problem_identification.md
Labels: documentation, milestone 1

#5 Denys documents
  .collaboration/communication.md
  .collaboration/learning_goals.md
Labels: documentation

#8 Deliverables for Milestone_1
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2_6_24,_11_45 AM_[Changes]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2_6_24,_11_45 AM_[Changes]1/shelved.patch
  milestones/1.problem_identification/problem_identification.md
  milestones/1.problem_identification/research_question.md
  milestones/1.problem_identification/system_design_thinking.md
Labels: documentation

#17 Google Trends Research ChatGPT Risks
  data_analysis/google_trends/README.md
  data_analysis/google_trends/data/google_trends_chatgpt_5.csv
  data_analysis/google_trends/data/google_trends_chatgpt_vs_soc_media.csv
  data_analysis/google_trends/img/google_trends_chatgpt_5.png
  data_analysis/google_trends/img/google_trends_chatgpt_vs_soc_media.png
Labels: documentation, milestone 3

#39 Update retrospective_of_4_communicating_results.md
  4_communicating_results/retrospective_of_4_communicating_results.md
Labels: milestone 4
